### ISSUE TITLE
too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by PaulineJac** [FoNDUE-HTR/Documentation#4]
I used this submission script:

```console
#!/bin/env bash
#SBATCH --partition=shared-gpu
#SBATCH --time=03:00:00
#SBATCH --gpus=1
#SBATCH --output=kraken-%j.out
#SBATCH --mem=0

module load fosscuda/2020b Python/3.8.6
source ~/Sandozenv/bin/activate

OUTPUT_NAME="output_name"
XML_FOLDER="/home/users/j/jacsont/Varios-OCR-files/Varios-GroundTruth/"

echo "KETOS training"
srun ketos train -o $OUTPUT_NAME -f page -d cuda "${XML_FOLDER}/*.xml"

```
How to debug this kind of error? 
```console
(Sandozenv) [jacsont@login1.yggdrasil Varios-OCR-files]$ cat kraken-7847534.out
KETOS training
WARNING:root:Torch version 1.10.0+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.9.1 is the most recent version that has been tested.
Traceback (most recent call last):
  File "/home/users/j/jacsont/Sandozenv/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/kraken/ketos.py", line 568, in train
    trainer = KrakenTrainer.recognition_train_gen(hyper_params,
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/kraken/lib/train.py", line 605, in recognition_train_gen
    training_data = preparse_xml_data(training_data, format_type, repolygonize)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/kraken/lib/dataset.py", line 302, in preparse_xml_data
    data = parse_fn(fn)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/kraken/lib/xml.py", line 165, in parse_page
    cs = _parse_page_custom(custom_str)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/kraken/lib/xml.py", line 109, in _parse_page_custom
    key, val = val.split(':')
ValueError: too many values to unpack (expected 2)
srun: error: gpu003: task 0: Exited with exit code 1
```

**Comment by gabays** [comment]
This Kraken not the cluster.
Try to add quotation marks around the path for the files:
```python
ketos train -f page -d cuda 'XML_Page/*xml'
```
I also recommend you use submission scripts.

**Comment by PaulineJac** [comment]
I just tried it, but I still get the same error ```ValueError: too many values to unpack (expected 2)```. 
I added the submission script to my first comment.

**Comment by gabays** [comment]
Script is not good: you do not close the brackets. -> `"` at the end of the `sbatch` command

**Comment by PaulineJac** [comment]
Sorry, it was a copy and paste error ... The brackets were present in my script...

**Comment by gabays** [comment]
Where are the data so that I can reproduce the error?

**Comment by PaulineJac** [comment]
I am sending you an invitation to our Github repository.

**Comment by gabays** [comment]
OK, I spent part of the day on this. So:
- problem comes from here: https://github.com/mittagessen/kraken/blob/f82b8a8afe283174315d067e3dee4eac5de5d0c8/kraken/lib/xml.py#L109
- In your page files you have `custom="structure {type:CustomZone:impresorNum;}"">` in which there is string corresponding to `\w+:\w+:\w+`. cf. here: https://github.com/DesenrollandoElCordel/Varios-OCR-files/blob/80a601f41243d7eec6ed1b3ee8f9785f5b4e2c57/Varios-GroundTruth/Moreno_007_1.xml#L242
- It creates a problem when the data are prepared before the training. If you use ALTO you should not have the problem

**Comment by gabays** [comment]
The problem should be corrected soon. Cf. https://github.com/mittagessen/kraken/pull/313

**Comment by PaulineJac** [comment]
Thank you very much for all your research and solutions: indeed, everything seems to work fine with ALTO! 
I will discuss with the other team members a transition to XML ALTO.

**Comment by PonteIneptique** [comment]
The fix has been merged, it will probably be available in a specific version at some point, otherwise, you can install the latest from the Kraken Master: https://github.com/mittagessen/kraken/pull/313

**Comment by PaulineJac** [comment]
Thank you very much for your help: everything seems to work now with PageXML.
