### ISSUE TITLE
`srun: error: gpu001: task 0: Out Of Memory`

### ISSUE THREAD

**Issue by gabays** [FoNDUE-HTR/Documentation#5]
Using the following submission script:

```bash
#!/bin/env bash
#SBATCH --partition=shared-gpu
#SBATCH --time=01:00:00
#SBATCH --gpus=pascal:1
#SBATCH --output=kraken-%j.out
#SBATCH --mem=0

module load GCCcore/10.2.0 Python/3.8.6
source ~/kraken-env/bin/activate

OUTPUT_NAME="output_name"
XML_FOLDER="/home/users/g/gabays/Documentation/data"

echo "KETOS training"
srun ketos segtrain -o $OUTPUT_NAME -f alto -d cuda "${XML_FOLDER}/*.xml"
```

I get the following error:

```console
(kraken-env) [gabays@gpu001.yggdrasil Documentation]$ bash submission_scripts/submission-seg.sh
KETOS training
WARNING:root:Torch version 1.10.0+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.9.1 is the most recent version that has been tested.
Creating model [1,1200,0,3 Cr7,7,64,2,2 Gn32 Cr3,3,128,2,2 Gn32 Cr3,3,128 Gn32 Cr3,3,256 Gn32 Cr3,3,256 Gn32 Lbx32 Lby32 Cr1,1,32 Gn32 Lby32 Lbx32 O2l13] with 13 outputs ✓
Training line types:
  Default	2	117
  DropCapitalLine	3	8
Training region types:
  RunningTitle	4	2
  Main	5	6
  Signatures	6	4
  Title	7	4
  Numbering	8	1
  Decoration	9	4
  DropCapital	10	4
  Stamp	11	1
  Damage	12	4
stage 1/50
Traceback (most recent call last):
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/ebsofts/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/opt/ebsofts/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1662) is killed by signal: Killed. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/users/g/gabays/kraken-env/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/kraken/ketos.py", line 353, in segtrain
    trainer.run(_print_eval, _draw_progressbar)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/kraken/lib/train.py", line 466, in run
    for _, batch in zip(range(self.event_it), self.train_set):
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/kraken/lib/dataset.py", line 371, in __next__
    sample = next(self.dataset_iter)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1142, in _get_data
    success, data = self._try_get_data()
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 1662) exited unexpectedly
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=7733274.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: gpu001: task 0: Out Of Memory
```

**Comment by gabays** [comment]
I have the same error with this script:
```bash
#!/bin/env bash
#SBATCH --partition=shared-gpu
#SBATCH --time=01:00:00
#SBATCH --gpus=pascal:1
#SBATCH --output=kraken-%j.out
#SBATCH --mem=0

module load GCCcore/10.2.0 Python/3.8.6
source ~/kraken-env/bin/activate

OUTPUT_NAME="output_name"
XML_FOLDER="/home/users/g/gabays/Documentation/data"

echo "KETOS training"
srun ketos train -o $OUTPUT_NAME -f alto -d cuda "${XML_FOLDER}/*.xml"

```

```console
bash submission_scripts/submission-rec.sh
KETOS training
WARNING:root:Torch version 1.10.0+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.9.1 is the most recent version that has been tested.
Building training set
Killed
(kraken-env) [gabays@gpu001.yggdrasil Documentation]$ slurmstepd: error: Detected 3 oom-kill event(s) in StepId=7733274.interactive cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: gpu001: task 0: Out Of Memory
```

**Comment by pkzli** [comment]
Hi, this one is surprising while you request all the memory of the node. But first remark, you should load the modules fosscuda/2020b and Python/3.8.6, rather than GCCcore. Maybe GCCcore works, but it's better to load the same module that have been used to install kraken in the slurm script. Then, if running on Yggdrasil, you should avoid restrict to pascal GPUs (I'm even surprised that this script starts running, while there is no pascal GPUs on Yggdrasil, see https://doc.eresearch.unige.ch/hpc/hpc_clusters#compute_nodes).

What dataset are you using ? so that I can try myself

**Comment by gabays** [comment]
I am using the one of this repo.
OK I will change this

**Comment by gabays** [comment]
Everything has been corrected. It seems to work:

```console
[gabays@login1.yggdrasil Documentation]$ sbatch submission_scripts/submission-rec.sh
Submitted batch job 7751272
```

( ping @PaulineJac )
