### ISSUE TITLE
`RuntimeError: DataLoader worker (pid 135271) is killed by signal: Killed. `

### ISSUE THREAD

**Issue by gabays** [FoNDUE-HTR/Documentation#7]
Submission script is:
```console
#!/bin/env bash
#SBATCH --partition=shared-gpu
#SBATCH --time=12:00:00
#SBATCH --gpus=1
#SBATCH --output=kraken-%j.out
#SBATCH --mem=0

module load fosscuda/2020b Python/3.8.6
source ~/kraken-env/bin/activate

OUTPUT_NAME="output_name"
XML_FOLDER="/home/users/g/gabays/Tobias/data"

echo "KETOS training"
srun ketos train -o $OUTPUT_NAME -f alto -d cuda "${XML_FOLDER}/*.xml"
```

Error is

```console 
(kraken-env) [gabays@gpu003.yggdrasil Tobias]$ ketos train -f alto -d cuda data/*xml

WARNING:root:Torch version 1.10.0+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.9.1 is the most recent version that has been tested.
Building training set  [#######-----------------------------]  690/3189[89.0849] Text line " " is empty after transformations 
Building training set  [#########---------------------------]  829/3189[89.1526] Text line " " is empty after transformations 
Building training set  [###################################-]  3167/3189  00:00:00[90.2198] Text line " " is empty after transformations 
Building training set  [####################################]  3189/3189          
Building validation set  [####################################]  336/336[90.3545] alphabet mismatch: chars in training set only: {'ꝓ', ';', 'Û', 'ꝯ', '(', 'ȝ', 'X', 'ô', 'ß', '̀', 'Ù', 'ʼ', '̂', 'è', 'ë', 'ꝝ', 'ꝑ', 'ü', '8', 'ꝙ', ')', 'ê', 'ƺ', 'õ', 'Q'} (not included in accuracy test during training) 
[90.3546] alphabet mismatch: chars in validation set only: {'\uf2f7', 'ͥ'} (not trained) 
Initializing model ✓
stage 1/∞  [------------------------------------]  0/3186
Traceback (most recent call last):
  File "/home/users/g/gabays/kraken-env/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/kraken/ketos.py", line 603, in train
    trainer.run(_print_eval, _draw_progressbar)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/kraken/lib/train.py", line 483, in run
    loss.backward()
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
  File "/home/users/g/gabays/kraken-env/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 135271) is killed by signal: Killed. 
(kraken-env) [gabays@gpu003.yggdrasil Tobias]$ 
```

**Comment by pkzli** [comment]
What is the dataset used in this case ? Can I access it ?

**Comment by gabays** [comment]
Hey Pierre, 
Here is the data: https://github.com/FoNDUE-HTR/FONDUE-MSS-GMH

**Comment by elodiepaupe** [comment]
Hi @gabays and @pkzli,
Do you find a solution? I have the same problem… The data are here: https://github.com/aaeb-porrentruy/corpus_prevot_farine_fr

**Comment by pkzli** [comment]
I was not able to reproduce the problem. Does it happen systematically ? Does it happen only when you connect interactively (salloc and then the command) or when you submit via sbatch as well ?

Could you try to add the line 
```
echo $SLURM_NODELIST
```
before
``` 
echo "KETOS training"
```
in the submission script and submit the job via the sbatch tool ? 
```
sbatch submission_script.sh
```

Here is the type of output I get :+1: 

```
[kuenzlip@login1.yggdrasil corpus_prevot_farine_fr]$ cat kraken-10235620.out
gpu008
KETOS training
Building training set
Building validation set
[1308.5040] alphabet mismatch: chars in training set only: {'?', '#', 'è', 'ù', '☨', 'â', 'î', 'ä'} (not included in accuracy test during training) 
Initializing model ✓
stage 1/∞
Accuracy report (1) 0.2242 24170 18751
stage 2/∞
Accuracy report (2) 0.4904 24170 12316
stage 3/∞
Accuracy report (3) 0.6353 24170 8816
stage 4/∞
Accuracy report (4) 0.7223 24170 6711
stage 5/∞
Accuracy report (5) 0.7846 24170 5207
stage 6/∞
Accuracy report (6) 0.8145 24170 4483
stage 7/∞
Accuracy report (7) 0.8479 24170 3677
stage 8/∞
```

**Comment by pkzli** [comment]
I don't understand why you launch the job with sbatch and then directly with ketos. The line with 
```
sbatch submission_scripts.sh
```

should already ask the computation with ketos, and you should see the corresponding output in a file named

```
kraken...out
```

for example
```
kraken-10240135.out
```

in your case.

Could you see if you have such files created and what is their content ?

**Comment by elodiepaupe** [comment]
The content of the file is: 
```
gpu008
KETOS training
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│                                                                              │
│ /home/users/p/paupeel1/kraken-env/bin/ketos:8 in <module>                    │
│                                                                              │
│   5 from kraken.ketos import cli                                             │
│   6 if __name__ == '__main__':                                               │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])     │
│ ❱ 8 │   sys.exit(cli())                                                      │
│   9                                                                          │
│ /home/users/p/paupeel1/kraken-env/lib/python3.8/site-packages/click/core.py: │
│ 1128 in __call__                                                             │
│                                                                              │
│ /home/users/p/paupeel1/kraken-env/lib/python3.8/site-packages/click/core.py: │
│ 1053 in main                                                                 │
│                                                                              │
│ /home/users/p/paupeel1/kraken-env/lib/python3.8/site-packages/click/core.py: │
│ 1659 in invoke                                                               │
│                                                                              │
│ /home/users/p/paupeel1/kraken-env/lib/python3.8/site-packages/click/core.py: │
│ 1395 in invoke                                                               │
│                                                                              │
│ /home/users/p/paupeel1/kraken-env/lib/python3.8/site-packages/click/core.py: │
│ 754 in invoke                                                                │
│                                                                              │
│ /home/users/p/paupeel1/kraken-env/lib/python3.8/site-packages/click/decorato │
│ rs.py:26 in new_func                                                         │
│                                                                              │
│ /home/users/p/paupeel1/kraken-env/lib/python3.8/site-packages/kraken/ketos.p │
│ y:573 in train                                                               │
│                                                                              │
│    570 │   if device == 'cpu':                                               │
│    571 │   │   device = None                                                 │
│    572 │   elif device.startswith('cuda'):                                   │
│ ❱  573 │   │   device = [int(device.split(':')[-1])]                         │
│    574 │                                                                     │
│    575 │   if hyper_params['freq'] > 1:                                      │
│    576 │   │   val_check_interval = {'check_val_every_n_epoch': int(hyper_pa │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: invalid literal for int() with base 10: 'cuda'
srun: error: gpu008: task 0: Exited with exit code 1
```

**Comment by pkzli** [comment]
@gabays could you try adding 

```
#SBATCH --ntasks=4
```

to your submission script ? add it as well to any interactive job allocation.

kraken uses torch to process data, and processes dedicated to loading data are created. For whatever reason I had version of modules that did not created those separated processes.

I tried to set ntasks to 2 but it still crashes. It seems to work with 4 (still waiting for the termination of a full execution).

**Comment by gabays** [comment]
Done

**Comment by pkzli** [comment]
yes
