### ISSUE TITLE
``RuntimeError: DataLoader worker (pid 343253) is killed by signal: Killed. ``

### ISSUE THREAD

**Issue by PaulineJac** [FoNDUE-HTR/Documentation#8]
Hello, 
I would like to test the model that I have trained with this command: 

``ketos test -m /Models-htr-Varios/Alto/Model-htr-v6/model_best.mlmodel -e /Split/test.txt -f alto``

And I get this error 

`````
(Sandozenv) [jacsont@gpu002.yggdrasil Varios-OCR-files]$ ketos test -m /Models-htr-Varios/Alto/Model-htr-v6/model_best.mlmodel -e /Split/test.txt -f alto 
WARNING:root:Torch version 1.10.0+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.9.1 is the most recent version that has been tested.
Loading model /home/users/j/jacsont/Varios-OCR-files/Models-htr-Varios/Alto/Model-htr-v6/model_best.mlmodel	✓
Evaluating /home/users/j/jacsont/Varios-OCR-files/Models-htr-Varios/Alto/Model-htr-v6/model_best.mlmodel
Evaluating  [#-----------------------------------]    3%  00:11:11
Traceback (most recent call last):
  File "/home/users/j/jacsont/Sandozenv/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/kraken/ketos.py", line 747, in test
    pred = net.predict_string(im, lens)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/kraken/lib/models.py", line 116, in predict_string
    o, olens = self.forward(line, lens)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/kraken/lib/models.py", line 79, in forward
    o, olens = self.nn.nn(line, lens)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/kraken/lib/layers.py", line 27, in forward
    inputs = module(*inputs)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/kraken/lib/layers.py", line 666, in forward
    seq_len = torch.clamp(torch.floor(
  File "/home/users/j/jacsont/Sandozenv/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 343253) is killed by signal: Killed. 
`````
Thanks for your help.

**Comment by PaulineJac** [comment]
Hello everyone, 
 I don't know if this helps but I get a similar error when I run fine tuning with this command:

`` ketos train -i /home/users/j/jacsont/Varios-OCR-files/Models/Models-htr-Varios/Alto/Model-htr-test-Niblack/model_best.mlmodel -f alto -d cuda --resize add /home/users/j/jacsont/Out-Of-Domain/Data/*.xml ``

The resulting error is: 

`RuntimeError: DataLoader worker (pid 58906) is killed by signal: Killed.`. 

This is also similar to the error obtained by @gabays [here](https://github.com/FoNDUE-HTR/Documentation/issues/7)
Thanks for your help.

**Comment by elodiepaupe** [comment]
@PaulineJac and you have find a solution? Because I have the same issue here...

**Comment by PaulineJac** [comment]
> @PaulineJac and you have find a solution? Because I have the same issue here...

Hi Elodie, 

I finally downloaded Kraken to my machine to test my models directly on it. 
I didn't  find a solution for the fine-tuning...

**Comment by elodiepaupe** [comment]
Ok. Thank you!

**Comment by pkzli** [comment]
Hello @PaulineJac , do you still have the same problem ? On which dataset ? Did you try using a submission script rather than using an interactive session ? I tried to reproduce the problem but couldn't manage to.

**Comment by PaulineJac** [comment]
Good evening @pkzli, 

In fact, everything works, whether to test a model or do a fine-tuning (I have not tried again since...) 

I tested my model with this command for my [corpus](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset): 
`ketos test -m FoNDUE-Spanish-chapbooks-Dataset/Models/Models-HTR-Varios/Model-htr-test-Niblack/model_best.mlmodel -e  FoNDUE-Spanish-chapbooks-Dataset/Grountruth/Split/test.txt -f alto`

And I ran the fine-tuning on my corpus with this command : 
```
#!/bin/env bash
#SBATCH --partition=public-gpu
#SBATCH --time=2-00:00:00
#SBATCH --gpus=1
#SBATCH --output=kraken-%j.out
#SBATCH --mem=0

module load fosscuda/2020b Python/3.8.6
source ~/Sandozenv/bin/activate

work_directory="/home/users/j/jacsont/FoNDUE-Spanish-chapbooks-Dataset/Models/Models-HTR-Varios/FT_test"
mkdir -p ${work_directory}
cd ${work_directory}

OUTPUT_NAME="output_name"

echo "KETOS training"
ketos train -f alto  -i /home/users/j/jacsont/FoNDUE-Spanish-chapbooks-Dataset/Models/Models-HTR-Varios/Model-htr-test-Niblack/model_best.mlmodel /home/users/j/jacsont/FoNDUE-Spanish-chapbooks-Dataset/Grountruth/Data+varios/*.xml

```

Nice evening to you.
